// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBes2Gipvn64GbFhNMEpHi0jCDTYHLyzbk',
    appId: '1:238886405153:web:422ef84fa9fc55cc670f60',
    messagingSenderId: '238886405153',
    projectId: 'estatepay1',
    authDomain: 'estatepay1.firebaseapp.com',
    databaseURL: 'https://estatepay1-default-rtdb.firebaseio.com',
    storageBucket: 'estatepay1.appspot.com',
    measurementId: 'G-L50K7Z63FW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUZKxrSK6nkMzS8FyoKN0IWdE0GIKncy8',
    appId: '1:238886405153:android:fb3035351e3b96b4670f60',
    messagingSenderId: '238886405153',
    projectId: 'estatepay1',
    databaseURL: 'https://estatepay1-default-rtdb.firebaseio.com',
    storageBucket: 'estatepay1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFcKboYXUmReMQafq6NtrUzFjTIm4f9BQ',
    appId: '1:238886405153:ios:a272ada3966e09ab670f60',
    messagingSenderId: '238886405153',
    projectId: 'estatepay1',
    databaseURL: 'https://estatepay1-default-rtdb.firebaseio.com',
    storageBucket: 'estatepay1.appspot.com',
    iosClientId: '238886405153-lfhnptck1i9ldtdj9shs20t14q0o4n8a.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );
}
